version: "3.5"

services:
  app:
    build:
      context: "."
      args:
        uid: ${UID}
    tty: true
    container_name: abf-app
    ports:
      - ${LOCAL_PORT}:80
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  db:
    image: mysql:5.7
    container_name: abf-db
    restart: unless-stopped
    tty: true
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web11265_1
      MYSQL_USER: web11265_1
      MYSQL_PASSWORD: ushBuichsapGad)
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network
