import {
    cibFacebook,
    cibTwitter,
    cibLinkedin,
    cibFlickr,
    cibTumblr,
    cibXing,
    cibGithub,
    cibStackoverflow,
    cibYoutube,
    cibDribbble,
    cibInstagram,
    cibPinterest,
    cibVk,
    cibYahoo,
    cibBehance,
    cibReddit,
    cibVimeo,
    cibCcMastercard,
    cibCcVisa,
    cibStripe,
    cibPaypal,
    cibGooglePay,
    cibCcAmex,
} from "@coreui/icons";
import { cifUs, cifBr, cifIn, cifFr, cifEs, cifPl } from "@coreui/icons";
import {
    // cilArrowRight,
    cilBan,
    // cilBasket,
    // cilBell,
    // cilCalculator,
    cilCalendar,
    // cilCloudDownload,
    cilCloudUpload,
    // cilChartPie,
    // cilCheck,
    // cilChevronBottom,
    // cilChevronTop,
    cilCheckCircle,
    // cilCommentSquare,
    cilContact,
    // cilCursor,
    cilCursorMove,
    // cilDrop,
    // cilDollar,
    // cilEnvelopeClosed,
    // cilEnvelopeOpen,
    // cilEuro,
    cilExitToApp,
    cilFile,
    cilFilter,
    // cilGlobeAlt,
    // cilGrid,
    // cilJustifyCenter,
    // cilLaptop,
    // cilLayers,
    // cilLightbulb,
    // cilList,
    // cilLocationPin,
    // cilLockLocked,
    cilLowVision,
    // cilMagnifyingGlass,
    // cilMoon,
    cilNewspaper,
    cilNotes,
    // cilOptions,
    cilPencil,
    cilPeople,
    // cilPuzzle,
    cilSettings,
    // cilShieldAlt,
    cilSpeech,
    cilSpeedometer,
    // cilStar,
    // cilTask,
    cilTrash,
    cilUser,
    // cilUserFemale,
    cilUserFollow,
    // cilXCircle,
} from "@coreui/icons";
import { logo } from "./logo";

export const iconsSet = Object.assign(
    {},
    { logo },
    {
        // cilArrowRight,
        cilBan,
        // cilBasket,
        // cilBell,
        // cilCalculator,
        cilCalendar,
        // cilCloudDownload,
        cilCloudUpload,
        // cilChartPie,
        // cilCheck,
        // cilChevronBottom,
        // cilChevronTop,
        cilCheckCircle,
        cilContact,
        cilCursorMove,
        // cilCommentSquare,
        // cilCursor,
        // cilDrop,
        // cilDollar,
        // cilEnvelopeClosed,
        // cilEnvelopeOpen,
        // cilEuro,
        cilExitToApp,
        cilFile,
        cilFilter,
        // cilGlobeAlt,
        // cilGrid,
        // cilFile,
        // cilJustifyCenter,
        // cilLaptop,
        // cilLayers,
        // cilLightbulb,
        // cilList,
        // cilLocationPin,
        // cilLockLocked,
        cilLowVision,
        // cilMagnifyingGlass,
        // cilMoon,
        cilNewspaper,
        cilNotes,
        // cilOptions,
        cilPencil,
        cilPeople,
        // cilPuzzle,
        cilSettings,
        // cilShieldAlt,
        cilSpeech,
        cilSpeedometer,
        // cilStar,
        // cilTask,
        cilTrash,
        cilUser,
        // cilUserFemale,
        cilUserFollow,
        // cilXCircle,
    },
    {
        cifUs,
        cifBr,
        cifIn,
        cifFr,
        cifEs,
        cifPl,
    },
    {
        cibFacebook,
        cibTwitter,
        cibLinkedin,
        cibFlickr,
        cibTumblr,
        cibXing,
        cibGithub,
        cibStackoverflow,
        cibYoutube,
        cibDribbble,
        cibInstagram,
        cibPinterest,
        cibVk,
        cibYahoo,
        cibBehance,
        cibReddit,
        cibVimeo,
        cibCcMastercard,
        cibCcVisa,
        cibStripe,
        cibPaypal,
        cibGooglePay,
        cibCcAmex,
    }
);
