name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: hub.docker.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Compose
        env:
          LOCAL_PORT: 8080
          UID: 1000
        run: docker-compose up -d
      - name: Deploy
        run: ./php-artisan deploy
