name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Container
        env:
          LOCAL_PORT: 8080
          UID: 1000
        run: docker-compose up -d
      - name: Deploy
        run: ./php-artisan deploy
