name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login Dockerhub
        run: |
          echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Create .env file
        run: |
          echo "DEPLOY_PATH=${{ secrets.DEPLOY_PATH }}" >> .env
          echo "SSH_USER=${{ secrets.SSH_USER }}" >> .env
          echo "SSH_PORT=${{ secrets.SSH_PORT }}" >> .env

      - name: Docker Compose
        env:
          LOCAL_PORT: 8080
          UID: 1000
        run: docker-compose up -d

      - name: Install composer dependencies
        run: |
          docker exec abf-app composer install

      - name: Deploy
        run: |
          docker exec abf-app /usr/bin/expect -c "set timeout -1; spawn php artisan deploy; expect -re \"password\"; send \"${{ secrets.SSH_PASSWORD }}\n\"; expect -re \"Successfully deployed\";"
