name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Container
        env:
          LOCAL_PORT: 8080
        run: |
          echo "::set-env name=UID::$(echo $UID)"
          docker-compose up -d

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy website
        run: |
          ./php-artisan deploy
