name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login Dockerhub
        run: |
          echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Docker Compose
        env:
          LOCAL_PORT: 8080
          UID: 1000
        run: docker-compose up -d

      - name: Deploy
        run: ./php-artisan deploy
