name: Pint

on:
  pull_request: null

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: "ramsey/composer-install@v3"

      - run: vendor/bin/pint -v
