name: Pint

on:
  pull_request: null

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RECTOR }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: "ramsey/composer-install@v3"

      - run: vendor/bin/pint -v

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[pint] Pint style fixes"
          commit_author: "GitHub Action <actions@github.com>"
          commit_user_email: "action@github.com"
