# github action that checks code with Rector
name: Rector

on:
  pull_request: null

jobs:
  rector:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: "ramsey/composer-install@v2"

      - run: vendor/bin/rector --ansi

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[rector] Rector fixes"
          commit_author: "GitHub Action <actions@github.com>"
          commit_user_email: "action@github.com"
