name: Test Suite

on: pull_request

jobs:
  build:
    name: Build and Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Docker Compose
        run: |
          docker run --rm \
          -v $(pwd):/opt \
          -w /opt \
          laravelsail/php80-composer:latest \
          composer update --no-interaction --no-progress  --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Setup app
        run: |
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan config:cache
          ./vendor/bin/sail artisan route:cache
          ./vendor/bin/sail npm install
          ./vendor/bin/sail npm run prod
          ./vendor/bin/sail artisan migrate --seed
          ./vendor/bin/sail artisan storage:link

      - name: Test PHP
        run: |
          ./vendor/bin/sail artisan serve &
          ./vendor/bin/sail vendor/bin/pest

      - name: Test EasyAdmin
        working-directory: ./resources/easyadmin
        run: |
          npm install
          npm run build --if-present
          npm run test:unit
        env:
          CI: true

  automerge:
    name: Automerge Dependabot Pull Request
    runs-on: ubuntu-latest
    needs: build
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!WIP"
          MERGE_METHOD: "squash"
